[package]
name = "d8"
version = "0.1.0"
authors = ["Quentin Leffray <leffray.quentin@bcg.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.35"
regex = "1.4.2"
