[package]
name = "d2"
version = "0.1.0"
authors = ["Quentin Leffray <leffray.quentin@bcg.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.8"
simplelog = "0.7.4"
