enum_discrim_align_threshold = 40
struct_field_align_threshold = 40
match_block_trailing_comma = true
overflow_delimited_expr = true
format_code_in_doc_comments = true
max_width = 120
# use_small_heuristics = "Off"
